#!/bin/bash

if [[ ! -d ~/local/cutesif ]] ;then
    cd /tmp/ && rm -rf CUTEst && git clone https://github.com/zaikunzhang/CUTEst
    mkdir -p ~/local
    mv /tmp/CUTEst/cutesif.7z ~/local
    cd ~/local && 7z x cutesif.7z
fi
