#!/bin/bash
# This script installs CUTEst on Linux, using the compiled CUTEst in $GITREPO.
# Last CUTEst update: 20220310

GITREPO="https://github.com/zaikunzhang/CUTEst"
REPONAME="$(basename "$GITREPO")"
TMPDIR="/tmp"
INSTALL_DIR="$HOME/local"
PKG="cutesif.7z"
PKG_NAME="${PKG//.*/}"
DECOMP="$(command -v 7z) x"

if [[ ! -d "$INSTALL_DIR"/"$PKG_NAME" ]] ;then
    cd "$TMPDIR" && rm -rf "$REPONAME" && git clone "$GITREPO"
    mkdir -p "$INSTALL_DIR"
    mv "$TMPDIR"/"$REPONAME"/$PKG "$INSTALL_DIR"
    cd "$INSTALL_DIR" && $DECOMP $PKG   # "$DECOMP $PKG" does not work
fi
